version: '3'
services:
  db:
    image: postgres:11.5
    hostname: postgres
    restart: 'always'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  web:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - RECIPE_FIEND_DATABASE_PASSWORD=test
      - DATABASE_URL=postgres://test@db:5432
volumes:
  pgdata:
